INITIAL_LIFE = 50
INITIAL_FARMS = 1
INITIAL_FOOD = 1
INITIAL_ARMY = 0

FARM_COST = 1
FARM_PROD_BONUS = 1
DEFENSE = 5

OPEN_BASELOSS = 0.7
OPEN_RESIDUALLOSS = 0.2
OPEN_CRITICALRATIO = 2
OPEN_DOMINANCERATIO = 3

SIEGE_BLOCKLOSS = 0.4
SIEGE_ATTACKERLOSS = 0.5
SIEGE_LOWBLOCKFACTOR = 0.2
SIEGE_HIGHBLOCKFACTOR = 0.6

PILHAGE_BASELOSS = 0.7
PILHAGE_DOMINANCERATIO = 1.5
PILHAGE_DAMAGEFACTOR = 0.1